### ISSUE TITLE
Orientation information

### ISSUE THREAD

**Issue by fferflo** [Jeff-Zilence/VIGOR#4]
Thanks for the great dataset!

I am working on a project where I require the orientation of the ground vehicle in addition to the panorama image. Since the panoramas are north-aligned, have you considered additionally publishing the vehicle's bearing per frame?

**Comment by Jeff-Zilence** [comment]
Thank you for your interest in this dataset. I do have the original unaligned orientation which may be the street direction (not sure), but it may take some time for me to get the data extracted and organized. You can give me your email so that I can share a sample with you to see if this is what you want.
