### ISSUE TITLE
random choice in dataloader.get_next_batch()

### ISSUE THREAD

**Issue by realxuyang** [Jeff-Zilence/VIGOR#6]
hello, why random choice according to sat instead of directly choice from panorama list? are there any special rules here?
![image](https://user-images.githubusercontent.com/45526497/196873069-e4961f52-9356-42cd-8828-5480d55978e1.png)

and why only feed the first satellite(aerial) image of each panorama(ground) instead of all of them? (self.train_label[img_idx][0])
![image](https://user-images.githubusercontent.com/45526497/196874474-d6ef4950-811b-4012-986f-6cadd7ef9364.png)

**Comment by Jeff-Zilence** [comment]
Thank you for your interest. 1) There is no special rule and you can use random selection from both panorama list or satellite. I used satellite because it has a balanced GPS distribution. Each satellite image may has 0-2 positive panorama images, so the GPS distribution of  panorama may not be perfectly balanced. But this would not have much effect, you can use it if you want. 
2) The first satellite is the positive (ground-truth) image for the query, the others are semi-positive images with smaller similarity. You might check this part in the paper.

**Comment by Jeff-Zilence** [comment]
I'll close the issue if there is no further question.
